"""
Developer release manager GUI for S drive deployment.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import tkinter as tk
from pathlib import Path
from tkinter import messagebox, ttk


SEMVER_PATTERN = re.compile(r"^v?\d+\.\d+\.\d+$")


class ReleaseManagerGUI:
    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        self.root.title("AI-parse Release Manager")
        self.root.geometry("900x680")
        self.root.minsize(820, 620)

        self.script_dir = Path(__file__).resolve().parent
        self.repo_root = self.script_dir.parent
        self.deploy_script = self.script_dir / "deploy_to_s_drive.ps1"
        self.switch_script = self.script_dir / "switch_release.ps1"

        self.target_root_var = tk.StringVar(value=r"S:\Uploading Team\AI-parse")
        self.operator_var = tk.StringVar(value=os.getenv("USERNAME", "developer"))
        self.new_version_var = tk.StringVar(value="")
        self.note_var = tk.StringVar(value="")
        self.current_version_var = tk.StringVar(value="-")

        self._build_ui()
        self.refresh_manifest()

    def _build_ui(self) -> None:
        container = ttk.Frame(self.root, padding=14)
        container.pack(fill=tk.BOTH, expand=True)

        top = ttk.LabelFrame(container, text="发布配置", padding=12)
        top.pack(fill=tk.X)

        ttk.Label(top, text="S盘目录").grid(row=0, column=0, sticky="w")
        ttk.Entry(top, textvariable=self.target_root_var, width=50).grid(row=0, column=1, sticky="we", padx=8)
        ttk.Button(top, text="刷新", command=self.refresh_manifest).grid(row=0, column=2, padx=4)

        ttk.Label(top, text="操作者").grid(row=1, column=0, sticky="w", pady=(8, 0))
        ttk.Entry(top, textvariable=self.operator_var, width=25).grid(row=1, column=1, sticky="w", padx=8, pady=(8, 0))

        ttk.Label(top, text="当前线上版本").grid(row=2, column=0, sticky="w", pady=(8, 0))
        ttk.Label(top, textvariable=self.current_version_var).grid(row=2, column=1, sticky="w", padx=8, pady=(8, 0))
        top.columnconfigure(1, weight=1)

        publish = ttk.LabelFrame(container, text="发布新版本", padding=12)
        publish.pack(fill=tk.X, pady=(12, 0))

        ttk.Label(publish, text="新版本号").grid(row=0, column=0, sticky="w")
        ttk.Entry(publish, textvariable=self.new_version_var, width=20).grid(row=0, column=1, sticky="w", padx=8)
        ttk.Label(publish, text="备注").grid(row=1, column=0, sticky="w", pady=(8, 0))
        ttk.Entry(publish, textvariable=self.note_var).grid(row=1, column=1, sticky="we", padx=8, pady=(8, 0))
        ttk.Button(publish, text="发布到S盘", command=self.deploy_release).grid(row=0, column=2, rowspan=2, padx=4)
        publish.columnconfigure(1, weight=1)

        mid = ttk.Panedwindow(container, orient=tk.HORIZONTAL)
        mid.pack(fill=tk.BOTH, expand=True, pady=(12, 0))

        versions_frame = ttk.Labelframe(mid, text="历史版本", padding=10)
        history_frame = ttk.Labelframe(mid, text="操作历史", padding=10)
        mid.add(versions_frame, weight=1)
        mid.add(history_frame, weight=1)

        self.release_list = tk.Listbox(versions_frame, height=12)
        self.release_list.pack(fill=tk.BOTH, expand=True)
        ttk.Button(versions_frame, text="回滚到选中版本", command=self.rollback_release).pack(fill=tk.X, pady=(8, 0))

        self.history_text = tk.Text(history_frame, height=12, state=tk.DISABLED)
        self.history_text.pack(fill=tk.BOTH, expand=True)

        log_frame = ttk.LabelFrame(container, text="执行日志", padding=10)
        log_frame.pack(fill=tk.BOTH, expand=True, pady=(12, 0))
        self.log_text = tk.Text(log_frame, height=10, state=tk.DISABLED)
        self.log_text.pack(fill=tk.BOTH, expand=True)

    def log(self, message: str) -> None:
        self.log_text.configure(state=tk.NORMAL)
        self.log_text.insert(tk.END, message + "\n")
        self.log_text.see(tk.END)
        self.log_text.configure(state=tk.DISABLED)
        self.root.update_idletasks()

    def _manifest_path(self) -> Path:
        return Path(self.target_root_var.get().strip()) / "release_manifest.json"

    def refresh_manifest(self) -> None:
        manifest_path = self._manifest_path()
        if not manifest_path.exists():
            self.current_version_var.set("(未找到 manifest)")
            self.release_list.delete(0, tk.END)
            self.history_text.configure(state=tk.NORMAL)
            self.history_text.delete("1.0", tk.END)
            self.history_text.insert(tk.END, "release_manifest.json 不存在\n")
            self.history_text.configure(state=tk.DISABLED)
            return

        try:
            # Accept both UTF-8 and UTF-8 BOM files generated by PowerShell.
            manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
        except Exception as exc:
            messagebox.showerror("读取失败", str(exc))
            return

        current = str(manifest.get("currentVersion", "")).strip() or "-"
        self.current_version_var.set(current)

        releases = manifest.get("releases", [])
        self.release_list.delete(0, tk.END)
        if isinstance(releases, list):
            sorted_versions = sorted(
                [str(r.get("version", "")).strip() for r in releases if isinstance(r, dict)],
                reverse=True,
            )
            for ver in sorted_versions:
                if ver:
                    self.release_list.insert(tk.END, ver)

        history = manifest.get("history", [])
        self.history_text.configure(state=tk.NORMAL)
        self.history_text.delete("1.0", tk.END)
        if isinstance(history, list):
            for item in history[-30:]:
                if not isinstance(item, dict):
                    continue
                line = (
                    f"{item.get('timestamp', '')} | {item.get('action', '')} | "
                    f"{item.get('fromVersion', '')} -> {item.get('toVersion', '')} | "
                    f"{item.get('operator', '')} | success={item.get('success', '')}\n"
                )
                self.history_text.insert(tk.END, line)
        self.history_text.configure(state=tk.DISABLED)

    def _validate_version(self, version: str) -> bool:
        return bool(SEMVER_PATTERN.match(version))

    def _run_script(self, script_path: Path, args: list[str]) -> None:
        command = [
            "powershell",
            "-NoProfile",
            "-ExecutionPolicy",
            "Bypass",
            "-File",
            str(script_path),
            *args,
        ]
        self.log("> " + " ".join(command))
        result = subprocess.run(command, capture_output=True, text=True, cwd=str(self.script_dir))
        if result.stdout.strip():
            self.log(result.stdout.strip())
        if result.stderr.strip():
            self.log(result.stderr.strip())
        if result.returncode != 0:
            raise RuntimeError(f"脚本执行失败，退出码={result.returncode}")

    def _run_cmd(self, command: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
        self.log("> " + " ".join(command))
        result = subprocess.run(command, capture_output=True, text=True, cwd=str(cwd))
        if result.stdout.strip():
            self.log(result.stdout.strip())
        if result.stderr.strip():
            self.log(result.stderr.strip())
        return result

    def _git_commit_and_push_for_release(self, version: str) -> None:
        status_result = self._run_cmd(["git", "status", "--porcelain"], cwd=self.repo_root)
        if status_result.returncode != 0:
            raise RuntimeError("无法读取 git 状态，请确认当前目录是有效仓库。")

        has_changes = bool(status_result.stdout.strip())
        if has_changes:
            add_result = self._run_cmd(["git", "add", "-A"], cwd=self.repo_root)
            if add_result.returncode != 0:
                raise RuntimeError("git add 失败。")

            commit_message = f"release: prepare {version}"
            commit_result = self._run_cmd(
                ["git", "commit", "-m", commit_message],
                cwd=self.repo_root,
            )
            if commit_result.returncode != 0:
                raise RuntimeError("git commit 失败。")
        else:
            self.log("无本地改动，跳过 git commit。")

        push_result = self._run_cmd(["git", "push"], cwd=self.repo_root)
        if push_result.returncode != 0:
            raise RuntimeError("git push 失败。")

    def deploy_release(self) -> None:
        version = self.new_version_var.get().strip()
        notes = self.note_var.get().strip()
        target_root = self.target_root_var.get().strip()
        operator = self.operator_var.get().strip() or "developer"

        if not self._validate_version(version):
            messagebox.showwarning("版本号无效", "版本号格式必须为 v1.2.3 或 1.2.3")
            return
        if not target_root:
            messagebox.showwarning("缺少路径", "请填写 S 盘目录")
            return

        if not messagebox.askyesno("确认发布", f"确认发布版本 {version} 到 {target_root} ?"):
            return

        try:
            self._git_commit_and_push_for_release(version)
            self._run_script(
                self.deploy_script,
                [
                    "-Version",
                    version,
                    "-TargetRoot",
                    target_root,
                    "-Operator",
                    operator,
                    "-Notes",
                    notes,
                ],
            )
            messagebox.showinfo("发布成功", f"版本 {version} 已发布")
            self.refresh_manifest()
        except Exception as exc:
            messagebox.showerror("发布失败", str(exc))

    def rollback_release(self) -> None:
        selected = self.release_list.curselection()
        if not selected:
            messagebox.showwarning("未选择版本", "请先从左侧列表选择要回滚到的版本")
            return

        version = self.release_list.get(selected[0]).strip()
        target_root = self.target_root_var.get().strip()
        operator = self.operator_var.get().strip() or "developer"

        if not messagebox.askyesno("确认回滚", f"确认将 current 切换到 {version} ?"):
            return

        try:
            self._run_script(
                self.switch_script,
                [
                    "-Version",
                    version,
                    "-TargetRoot",
                    target_root,
                    "-Operator",
                    operator,
                    "-Reason",
                    "rollback from release manager",
                ],
            )
            messagebox.showinfo("回滚成功", f"已切换到版本 {version}")
            self.refresh_manifest()
        except Exception as exc:
            messagebox.showerror("回滚失败", str(exc))


def main() -> None:
    root = tk.Tk()
    app = ReleaseManagerGUI(root)
    root.mainloop()


if __name__ == "__main__":
    main()
